import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jonas Berglund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jonas Berglund</h1>

        <p className={styles.description}>
          UX/UI Designer & Front-End Developer
        </p>
      </main>

      <footer className={styles.footer}>© 2021 Jonas Berglund</footer>
    </div>
  );
}
